## Learn About Numpy


In [14]:
import numpy as np

In [4]:
arr_1d = np.array([1, 2, 3, 4])
print("1D array : ", arr_1d )

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array :", arr_2d)

1D array :  [1 2 3 4]
2D array : [[1 2 3]
 [4 5 6]]


## List vs Numpy


In [5]:
py_list = [1,2,3]
print("Pyhton list multiplication", py_list*2)


Pyhton list multiplication [1, 2, 3, 1, 2, 3]


In [ ]:
np_array = np.array([1, 2, 3])
print("Python array multiplication", np_array*2)

Pyhton array multiplication [2 4 6]


In [ ]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time :", time.time() - start) # 0.10156512260437012

start = time.time()
np_array = np.arange(1000000)*2 
print("\n Numpy operation time :", time.time() - start) # 0.005458354949951172



 List operation time : 0.10156512260437012

 Numpy operation time : 0.005458354949951172


## Vector, Matrix, and Tensor

In [21]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matix: ", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6 ], [7, 8]]])
print("Tensor:", tensor)

Vector:  [1 2 3]
Matix:  [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [22]:
arr = np.array([[1,2,3],
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension", arr.ndim)
print("Size ", arr.size)
print("DataType", arr.dtype)

Shape  (2, 3)
Dimension 2
Size  6
DataType int64


## Arrange Reshaping

In [23]:
arr = np.arange(12)
print("Original Array", arr)

Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
reshaped = arr.reshape((3, 4))
print("\n Reshaped Array ", reshaped)
flattened = reshaped.flatten()
print("\n Falttened array ", flattened)





 Reshaped Array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Falttened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
raveled = reshaped.ravel() # ravel (return view , instead of copy)
print("\n Raveled array ", raveled)



 Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
#Transpose
transpose = reshaped.T
print("\n Transposed Array", transpose)


 Transposed Array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Creating Array from scratch


In [34]:
zeros = np.zeros((3,4))
print("zeros array : \n", zeros)

ones = np.ones((2,3))
print("ones array : \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequence array: \n", sequence)

zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.82979966 0.74069606 0.67913256]
 [0.06097934 0.67754481 0.09680103]]
sequence array: 
 [ 0  2  4  6  8 10]
