## Numpy Array Operations

In [2]:
import numpy as np

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing:", arr[2:7])

print("With step", arr[1:8:2])


Basic Slicing: [2 3 4 5 6]
With step [1 3 5 7]


In [7]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[1,2])

Specific element 6


In [8]:
print("Entire row", arr_2d[1])

Entire row [4 5 6]


In [10]:
print("Entire coloumn", arr_2d[:,1])

Entire coloumn [2 5 8]


## Sorting


In [12]:
unsorted = np.array([3,54, 5, 8, 77, 96,])
print("sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1,2], [2, 3]])
print("Sorted 2d array by coloumn", np.sort(arr_2d_unsorted))

sorted array [ 3  5  8 54 77 96]
Sorted 2d array by coloumn [[1 3]
 [1 2]
 [2 3]]


In [15]:
print("Sorted 2d array by coloumn", np.sort(arr_2d_unsorted, axis = 0))

Sorted 2d array by coloumn [[1 1]
 [2 2]
 [3 3]]


In [16]:
print("Sorted 2d array by coloumn", np.sort(arr_2d_unsorted, axis = 1))


Sorted 2d array by coloumn [[1 3]
 [1 2]
 [2 3]]


## Filters

In [17]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 ==0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [19]:
mask = numbers > 5
print("Numbers greater than 5 : ", numbers[mask])


Numbers greater than 5 :  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [21]:
print("numbers",numbers)
indices = [0, 2, 4]
print(numbers[indices])

numbers [ 1  2  3  4  5  6  7  8  9 10]
[1 3 5]


In [23]:
print(where_result)
where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])

(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [26]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


In [27]:
condition_array = np.where(numbers > 5, numbers*2, numbers*3)
print(condition_array)

[ 3  6  9 12 15 12 14 16 18 20]


In [28]:
condition_array = np.where(numbers > 5, "True", "False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


Back end process of above cell

if numbers > 5 :
    print("True")
else:
    print("False")    


## Adding and Remove Data

In [29]:
arr1 =np.array([1,2,3])
arr2 =np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)


[1 2 3 4 5 6]


## Array compatibility

In [32]:
a =np.array([1,2,3])
b =np.array([4,5,6])
c =np.array([7,8,9])
print("Compatibility shape", a.shape == b.shape, b.shape == c.shape )

Compatibility shape True True


In [36]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])
whith_new_row = np.vstack((original, new_row))
print("Original",original)
print("With_New_Row",whith_new_row)

Original [[1 2]
 [3 4]]
With_New_Row [[1 2]
 [3 4]
 [5 6]]


In [37]:
new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("whith_new_col", with_new_col)

whith_new_col [[1 2 7]
 [3 4 8]]


## Delete array


In [39]:
arr = np.array([0,1,2,3,4,5])
deleted = np.delete(arr, 2)
print("Array after deletion :", deleted)


Array after deletion : [0 1 3 4 5]


In [40]:
deleted = np.delete(arr, 3)
print("Array after deletion :", deleted)


Array after deletion : [0 1 2 4 5]


In [41]:
deleted = np.delete(arr, 4)
print("Array after deletion :", deleted)


Array after deletion : [0 1 2 3 5]
