# Student Score Analyze

In [1]:
import numpy as np

# Rows = students, Columns = subjects
data = np.array([
    [85, 90, 78],
    [60, 70, 65],
    [95, 88, 92],
    [40, 50, 45],
    [70, 75, 80]
])

print(data)

[[85 90 78]
 [60 70 65]
 [95 88 92]
 [40 50 45]
 [70 75 80]]


### Goal

Build a small system using NumPy that:

- Analyzes student scores
- Cleans data
- Computes statistics
- Applies filtering


In [5]:
# Average marks per student
student_avg1 = np.mean(data, axis=1)

# Average per subject
subject_avg2 = np.mean(data, axis=0) 

print(student_avg1) # Column wise
print(subject_avg2) # Row wise

[84.33333333 65.         91.66666667 45.         75.        ]
[70.  74.6 72. ]


In [11]:
#Who is topper ?
toppers = data[student_avg > 80]
print(toppers)

[[85 90 78]
 [95 88 92]]


In [16]:
A1 = [85, 90, 78]
A2=  [95, 88, 92]

x = np.where(data == A1)
print(x)

(array([0, 0, 0]), array([0, 1, 2]))


In [17]:
x2 = np.where(data == A2)
print(x2)

(array([2, 2, 2]), array([0, 1, 2]))


In [25]:
# Add grace marks
data[data < 50] += 10

print(data)

[[85 90 78]
 [60 70 65]
 [95 88 92]
 [50 50 55]
 [70 75 80]]


In [26]:
normalized = data / 100
print(normalized)

[[0.85 0.9  0.78]
 [0.6  0.7  0.65]
 [0.95 0.88 0.92]
 [0.5  0.5  0.55]
 [0.7  0.75 0.8 ]]


In [27]:
flat = data.reshape(-1)
print(flat)

[85 90 78 60 70 65 95 88 92 50 50 55 70 75 80]


In [28]:
data.shape

(5, 3)